# Generated by Django 4.1.6 on 2023-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='profile_images')),
                ('friends', models.ManyToManyField(to='HCS_AE.userprofile')),
            ],
        ),
    ]
